language: scala
dist: xenial
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test
scala:
  - 2.12.10
jdk:
  - oraclejdk11
  - openjdk11
  - openjdk8
before_script:
  - sudo chmod +x /usr/local/bin/sbt #https://github.com/travis-ci/travis-ci/issues/7703
sudo: required # for setting hostname
addons:
  hostname: localhost #https://github.com/travis-ci/travis-ci/issues/5227
notifications:
  email:
    - guntiso@uniso.lv
    - martins@uniso.lv
