language: scala
dist: xenial
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test
scala:
  - 2.13.2
  - 2.12.11
  - 2.11.12
  - 2.10.7
jdk:
  - oraclejdk11
  - openjdk11
  - openjdk8
notifications:
  email:
    - guntiso@uniso.lv
    - martins@uniso.lv
