language: scala
dist: xenial
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test versionPolicyCheck
scala:
  - 2.13.4
  - 2.12.13
  - 2.11.12
  - 2.10.7
jdk:
  - oraclejdk11
  - openjdk11
  - openjdk8
# addons:
#   postgresql: 9.6   # disabled because of language pack installation
before_install:
  - sudo apt-get update
  - sudo apt-get install language-pack-lv
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.6
before_script:
  - psql -f test/conf/querease-postgresql-setup.sql -U postgres
  - cp test/conf/application.conf.travis test/conf/application.conf
notifications:
  email:
    - guntiso@uniso.lv
    - martins@uniso.lv
