name: Build and test
on:   [push]
jobs:
  Build-and-test:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os:   [ubuntu-latest]  # TODO macos-latest, windows-latest
        java: [11] #, 17, 21]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Install language pack
      run: |
        sudo apt-get update
        sudo apt-get install language-pack-lv
    - name: Start PostgreSQL
      run: |
        sudo systemctl start postgresql.service
        pg_isready
    - name: Create user and databases
      run: |
        sudo -u postgres psql --command="CREATE ROLE querease LOGIN PASSWORD 'querease';"
        sudo -u postgres psql --command="CREATE DATABASE querease  with TEMPLATE template0 OWNER=querease LC_COLLATE='lv_LV.UTF-8' LC_CTYPE='lv_LV.UTF-8'"
        sudo -u postgres psql --command="CREATE DATABASE querease2 with TEMPLATE template0 OWNER=querease LC_COLLATE='lv_LV.UTF-8' LC_CTYPE='lv_LV.UTF-8'"
    - name: Configure tests
      run:  cp test/conf/application.conf.ci test/conf/application.conf
    - name: Compile and test and check version policy
      run:  sbt clean update +compile +test +versionPolicyCheck
