name: Build and test
on:   [push]
jobs:
  Build-and-test:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os:   [ubuntu-latest]  # TODO macos-latest, windows-latest
        java: [8, 11, 17]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Install language pack
      run: |
        sudo apt-get update
        sudo apt-get install language-pack-lv
    - name: Start PostgreSQL
      run: |
        sudo systemctl start postgresql.service
        pg_isready
    - name: Create user and database
      run: |
        sudo -u postgres psql -f $GITHUB_WORKSPACE/test/conf/querease-postgresql-setup.sql
    - name: Configure tests
      run:  cp test/conf/application.conf.ci test/conf/application.conf
    - name: Compile and test and check version policy
      run:  sbt clean update +compile +test +versionPolicyCheck
